server:
  port: 10000
  servlet:
    session:
      timeout: 30m

#每个微服务连接的数据库都各不相同
spring:
  application:
    name: gulimall-product
    #注册中心的名称---或者说整个应用的名称---有了名称别人才可以识别
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.77.130:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        #注册中心的地址

    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: localhost:8080

  redis:
    host: 192.168.77.130
    port: 6379

#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

    #关闭thymeleaf缓存
  thymeleaf:
    cache: false

  session:
    store-type: redis

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  #默认扫描的位置
  #就是项目的dao和xml文件相连接

  #设置实体类的自增主键
  global-config:
    db-config:
      id-type: auto
      #自增主键的设置
      #逻辑删除---目前实际的删除方法
      logic-delete-value: 1 #逻辑已删除---在具体的tablelogic中的value中可以另外设置
      logic-not-delete-value: 0 #逻辑未删除

logging:
  level:
    com.xunqi.gulimall: error


#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'